<?php
$title = 'All Movies';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('movie', array(
        'action'=>'add'));?>">Add new album</a></p>

<table class="table">
<tr>
    <th>Title</th>
    <th></th>
</tr>
<?php foreach($movies as $movie) :
    $movietitle = $this->escapeHtml($movie->title);
?>
<tr>
    <td><?php echo $movietitle;?></td>
    <td>
        <a href="<?php echo $this->url('movie',
            array('action'=>'edit', 'id' => $movie->id));?>">Edit</a>
        <a href="<?php echo $this->url('movie',
            array('action'=>'delete', 'id' => $movie->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>

